---
spring:
  jpa:
    generate-ddl: true
# turn off the security on the actuator end points as this is a demo app
management:
  security:
    enabled: false
security:
 oauth2:
  client:
   client-id: 1f3c9156-0d3b-4c3e-8677-0dc77c68f1d4
   client-secret: 7af11e3b-da68-449c-b9f9-e7489940d538
  resource:
   token-info-uri: http://localhost:8080/oauth/check_token
server:
 port: 8090