---
spring:
  jpa:
    generate-ddl: true
# turn off the security on the actuator end points as this is a demo app
management:
  security:
    enabled: false
security:
 basic:
  enabled: true
 user:
  name: user
  password: demo
